language: cpp

os:
  - linux
  - osx

script:
  - export TOP=$(pwd)
  - git clone https://github.com/MathiasMagnus/OpenCL-Headers.git --branch pkgconfig --single-branch
  - cd ${TOP}/OpenCL-Headers
  - ln -s CL OpenCL # For OSX builds
  - mkdir build
  - mkdir install
  - cd build
  - cmake -D CMAKE_INSTALL_PREFIX=../install
          ..
  - cmake --build .
          --target install
  - cd ${TOP}
  - git clone https://github.com/MathiasMagnus/OpenCL-ICD-Loader.git --branch pkgconfig --single-branch
  - cd ${TOP}/OpenCL-ICD-Loader
  - mkdir build
  - mkdir install
  - cd build
  - cmake -D CMAKE_INSTALL_PREFIX=../install
          -D CMAKE_PREFIX_PATH=${TOP}/OpenCL-Headers/install
          ..
  - cmake --build .
          --target install
  - cd ${TOP}
  - ls -l
  - mkdir build
  - mkdir install
  - cd build
  - cmake -D CMAKE_INSTALL_PREFIX=../install
          -D CMAKE_PREFIX_PATH=${TOP}/OpenCL-Headers/install ..
          -D CMAKE_PREFIX_PATH=${TOP}/OpenCL-ICD-Loader/install ..
          -D BUILD_TESTS=ON
          ..
  - cmake --build .
          --target install
  - ctest
