name: Presubmit
on: [push, pull_request]

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Fetch dependencies
        run: |
          git clone https://github.com/KhronosGroup/OpenCL-Headers.git
          cd OpenCL-Headers
          ln -s CL OpenCL # For OSX builds
          cd ..
          git clone https://github.com/KhronosGroup/OpenCL-ICD-Loader.git
      - name: Build loader
        run: |
          export TOP=$(pwd)
          cd OpenCL-ICD-Loader
          mkdir build
          cd build
          cmake -DOPENCL_ICD_LOADER_HEADERS_DIR=${TOP}/OpenCL-Headers/ ..
          cmake --build .
      - name: Build
        run: |
          export TOP=$(pwd)
          mkdir build
          cd build
          cmake -DOPENCL_LIB_DIR=${TOP}/OpenCL-ICD-Loader/build \
                -DOPENCL_INCLUDE_DIR=${TOP}/OpenCL-Headers \
                ..
          cmake --build .
      - name: Run tests
        run: |
          cd build
          ctest
